// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	models "github.com/Pythonyan3/payment-service/internal/models"
	
	gomock "github.com/golang/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUserTransactionsByEmail mocks base method.
func (m *MockUserService) GetUserTransactionsByEmail(userEmail string) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactionsByEmail", userEmail)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactionsByEmail indicates an expected call of GetUserTransactionsByEmail.
func (mr *MockUserServiceMockRecorder) GetUserTransactionsByEmail(userEmail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactionsByEmail", reflect.TypeOf((*MockUserService)(nil).GetUserTransactionsByEmail), userEmail)
}

// GetUserTransactionsById mocks base method.
func (m *MockUserService) GetUserTransactionsById(userId int) ([]*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTransactionsById", userId)
	ret0, _ := ret[0].([]*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTransactionsById indicates an expected call of GetUserTransactionsById.
func (mr *MockUserServiceMockRecorder) GetUserTransactionsById(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTransactionsById", reflect.TypeOf((*MockUserService)(nil).GetUserTransactionsById), userId)
}
